#!/usr/bin/env python3
import os
import argparse


def copy_pwd(args):
    if args.r:
        path = 'realpath ./'
    else:
        path = 'pwd'

    os.system('echo `%s`' % path)
    os.system('echo `%s` | pbcopy' % path)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-r', action='store_true')
    args = parser.parse_args()
    copy_pwd(args)



# vim: ts=4 sw=4 sts=4 expandtab
